//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vanlangcanteen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public ACCOUNT()
        {
            this.MENUs = new HashSet<MENU>();
            this.ORDERs = new HashSet<ORDER>();
            this.NOTIFICATIONs = new HashSet<NOTIFICATION>();
        }
    
        public int ID { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string FULL_NAME { get; set; }
        public bool STATUS { get; set; }
        public int ROLE { get; set; }
    
        public virtual ICollection<MENU> MENUs { get; set; }
        public virtual ICollection<ORDER> ORDERs { get; set; }
        public virtual ICollection<NOTIFICATION> NOTIFICATIONs { get; set; }
    }
}
