//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace vanlangcanteen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT()
        {
            this.MENUs = new HashSet<MENU>();
            this.ORDERs = new HashSet<ORDER>();
            this.NOTIFICATIONs = new HashSet<NOTIFICATION>();
        }
    
        public int ID { get; set; }
        public string EMAIL { get; set; }
        [Display(Name = "New Password")]
        [Required(ErrorMessage = "Không được để trống")]
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{8,15}$", ErrorMessage = "Mật khẩu không đúng")]
        public string PASSWORD { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public string FULL_NAME { get; set; }
        public bool STATUS { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public int ROLE { get; set; }
    
        public virtual ICollection<MENU> MENUs { get; set; }
        public virtual ICollection<ORDER> ORDERs { get; set; }
        public virtual ICollection<NOTIFICATION> NOTIFICATIONs { get; set; }
    }
}
