//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace vanlangcanteen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORY()
        {
            this.FOODs = new HashSet<FOOD>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [MaxLength(3, ErrorMessage = "chieu dai toi da la 3")]
        [MinLength(3, ErrorMessage = "chieu dai toi thieu la 3")]
        [RegularExpression(@"^(?=.*[A-Z]).{3,3}$", ErrorMessage = "Chưa đúng định dạng")]
        public string CATEGORY_CODE { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [MaxLength(100, ErrorMessage = "chieu dai toi da la 100")]
        [MinLength(3, ErrorMessage = "chieu dai toi thieu la 3")]
        public string CATEGORY_NAME { get; set; }
        public string IMAGE_URL { get; set; }
        public bool STATUS { get; set; }
    
        public virtual ICollection<FOOD> FOODs { get; set; }
    }
}
