//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vanlangcanteen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACULTY
    {
        public FACULTY()
        {
            this.CUSTOMERs = new HashSet<CUSTOMER>();
        }
    
        public int ID { get; set; }
        public string FACULTY_CODE { get; set; }
        public string FACULTY_NAME { get; set; }
        public bool STATUS { get; set; }
    
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
    }
}
