//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace vanlangcanteen.Models
{
    using System;
    using System.Collections.Generic;

    public partial class FOOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOOD()
        {
            this.MENUs = new HashSet<MENU>();
        }

        public int ID { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [MinLength(6, ErrorMessage = "Bắt buộc có 6 ký tự")]
        [MaxLength(6, ErrorMessage = "Bắt buộc có 6 ký tự")]
        [RegularExpression(@"^(?=.*[A-Z])(?=.*[0-9]).{6,6}$", ErrorMessage = "Chưa đúng định dạng")]
        public string FOOD_CODE { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [MinLength(1, ErrorMessage = "Chiều dài tối thiểu là 1 ký tự")]
        [MaxLength(1000, ErrorMessage = "Chiều dài tối đa là 1000 ký tự")]
        public string FOOD_NAME { get; set; }
        public int CATEGORY_ID { get; set; }

        //[Required(ErrorMessage = "Không được để trống")]
        //[MinLength(1, ErrorMessage = "Chiều dài tối thiểu là 1 ký tự")]
        //[MaxLength(1000, ErrorMessage = "Chiều dài tối đa là 1000 ký tự")]
        public string DESCRIPTION { get; set; }
        [DisplayFormat(DataFormatString ="{0:C}")]
        [Required(ErrorMessage = "Không được để trống")]
        [Range(1000,1000000,ErrorMessage ="Giá tối thiểu là 1000 đến 1000000")]
        public int PRICE { get; set; }
        public string IMAGE_URL { get; set; }
        public bool STATUS { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual ICollection<MENU> MENUs { get; set; }
    }
}
